[package]
name              = "rustkvm"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true

[lib]
name        = "rustkvm"
crate-type  = ["staticlib", "rlib"]

[[bin]]
name = "rustkvm_app"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
# Error
anyhow.workspace             = true

# Async
tokio.workspace              = true
tokio-tungstenite.workspace  = true
tokio-util.workspace         = true
futures.workspace            = true
futures-util.workspace       = true

# Serde
serde.workspace              = true
serde_json.workspace         = true
toml.workspace               = true

# Tracing
tracing.workspace            = true
tracing-subscriber.workspace = true

# Sync
parking_lot.workspace        = true
once_cell.workspace          = true

# Time
chrono.workspace             = true
time.workspace               = true

# Crypto / Auth
sha2.workspace               = true
bcrypt.workspace             = true
rustls.workspace             = true
rcgen.workspace              = true

# HTTP
reqwest.workspace            = true
httpdate.workspace           = true

# Web frameworks
salvo.workspace              = true
socketioxide.workspace       = true

# System / IO
libc.workspace               = true
rustix.workspace             = true
if-addrs.workspace           = true
mdns-sd.workspace            = true
macaddr.workspace            = true
nbd.workspace                = true

# Encoding / Misc
base64.workspace             = true
hex.workspace                = true
bytes.workspace              = true
uuid.workspace               = true
regex.workspace              = true
clap.workspace               = true
dotenvy.workspace            = true
prometheus.workspace         = true
rust-embed.workspace         = true
zip.workspace                = true

# Protocols
rumqttc.workspace            = true
webrtc.workspace             = true

# GStreamer
gstreamer.workspace          = true
gstreamer-app.workspace      = true
gstreamer-video.workspace    = true

# Git deps
id_token_verifier.workspace  = true

# Internal crates
rkvm-core.workspace          = true
rkvm-net.workspace           = true

[dev-dependencies]
tempfile.workspace           = true
