[package]
name = "rustkvm"
version = "0.1.0"
edition = "2024"

[lib]
name = "rustkvm"
crate-type = ["staticlib", "rlib"]

[[bin]]
name = "rustkvm_app"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.98"
base64 = { version = "0.22.1", default-features = false }
bcrypt = { version = "0.17.0", default-features = false, features = ["std"] }
chrono = { version = "0.4.42", default-features = false, features = ["alloc"] }
clap = { version = "4.5.53", default-features = false, features = [
    "derive",
    "env",
    "cargo",
    "std",
    "help",
    "usage",
    "error-context",
    "string",
] }
dotenvy = "0.15"
futures = { version = "0.3.31", default-features = false }
futures-util = { version = "0.3.31", default-features = false }
gstreamer = { version = "0.24.2", features = ["v1_22"] }
gstreamer-app = { version = "0.24.2", features = ["v1_22"] }
gstreamer-video = { version = "0.24.2", features = ["v1_22"] }
hex = { version = "0.4.3", default-features = false }
httpdate = "1.0.3"
id_token_verifier = { git = "https://github.com/foxxcn/id_token_verifier.git", tag = "rustkvm", features = [
    "tracing",
] }
if-addrs = "0.14.0"
libc = { version = "0.2.175", default-features = false }
macaddr = { version = "1.0.1", default-features = false }
mdns-sd = { version = "0.15.1", default-features = false }
nbd = "0.3.1"
once_cell = "1.21.3"
parking_lot = "0.12.4"
prometheus = { version = "0.14.0", default-features = false }
rcgen = { version = "0.14.3", features = ["pem"] }
regex = { version = "1.11.1", default-features = false }
reqwest = { version = "0.12.23", default-features = false, features = [
    "blocking",
    "rustls-tls-webpki-roots",
    "json",
] }
rust-embed = "8.7.2"
rustix = { version = "1.0.8", default-features = false, features = [
    "pty",
    "fs",
    "termios",
    "net",
] }
rustls = { version = "0.23.29", default-features = false, features = [
    "ring",
] } # or "aws_lc_rs"
salvo = { version = "0.84.0", features = [
    "oapi",
    "serve-static",
    "tower-compat",
    "websocket",
    "compression",
] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
socketioxide = { version = "0.17.2", features = ["extensions", "state"] }
time = { version = "0.3.41", default-features = false, features = ["macros"] }
tokio = { version = "1.46.1", features = ["full", "macros"] }
tokio-tungstenite = { version = "0.28.0", default-features = false, features = [
    "connect",
    "rustls-tls-webpki-roots",
] }
tokio-util = { version = "0.7.16", default-features = false }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["json"] }
uuid = { version = "1.17.0", default-features = false, features = ["v4"] }
webrtc = { version = "0.14.0", features = [] }

[dev-dependencies]
tempfile = "3.20.0"
