[target.aarch64-unknown-linux-gnu]
linker = "/opt/rk3588-buildkit/bin/aarch64-buildroot-linux-gnu-gcc"

[env]
PKG_CONFIG_ALLOW_CROSS = "1"
PKG_CONFIG_SYSROOT_DIR = "/opt/rk3588-buildkit/aarch64-buildroot-linux-gnu/sysroot"
PKG_CONFIG_PATH = "/opt/rk3588-buildkit/aarch64-buildroot-linux-gnu/sysroot/usr/lib/pkgconfig"
PKG_CONFIG_LIBDIR = "/opt/rk3588-buildkit/aarch64-buildroot-linux-gnu/sysroot/usr/lib/pkgconfig"
