
[package]
name        = "rkvm-web"
version     = "0.1.0"
edition     = "2024"
license     = "GPL-2.0-only"
repository  = "https://github.com/Rust-KVM/rustkvm"
[workspace]

[dependencies]
base64      = "0.22"
console_error_panic_hook = "0.1"
futures     = { version = "0.3", default-features = false, features = ["std", "async-await"] }
gloo-net    = { version = "0.7", features = ["http", "websocket"] }
gloo-timers = { version = "0.4", features = ["futures"] }
js-sys               = "0.3"
leptos               = { version = "0.8", features = ["csr"] }
rkvm-proto           = { path = "../rkvm-proto" }
serde       = { version = "1", features = ["derive"] }
serde_json  = "1"
tracing     = "0.1"
tracing-wasm = "0.2"
vt100 = "0.16.2"
wasm-bindgen         = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = [
    "Window",
    "Document",
    "Element",
    "HtmlVideoElement",
    "HtmlMediaElement",
    "MediaStream",
    "RtcPeerConnection",
    "RtcConfiguration",
    "RtcIceServer",
    "RtcSdpType",
    "RtcSessionDescription",
    "RtcSessionDescriptionInit",
    "RtcPeerConnectionIceEvent",
    "RtcIceGatheringState",
    "RtcIceConnectionState",
    "RtcIceCandidate",
    "RtcIceCandidateInit",
    "RtcDataChannel",
    "RtcDataChannelInit",
    "RtcDataChannelState",
    "RtcTrackEvent",
    "RtcRtpTransceiver",
    "RtcRtpTransceiverInit",
    "RtcRtpTransceiverDirection",
    "RtcDataChannelType",
    "MessageEvent",
    "Event",
    "EventTarget",
    "RequestCredentials",
    "console",
    "KeyboardEvent",
    "MouseEvent",
    "WheelEvent",
    "File",
    "FileList",
    "Blob",
    "HtmlElement",
    "HtmlDivElement",
    "HtmlInputElement",
    "HtmlTextAreaElement",
    "HtmlSelectElement",
    "HtmlCanvasElement",
    "CanvasRenderingContext2d",
] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
